### ISSUE TITLE
Metric 'Detection: Sequential' gives ValueError for datetime column

### ISSUE THREAD

**Issue by Scit3ch** [sdv-dev/SDMetrics#580] opened 2024-06-04 07:50 UTC
### Environment Details

* SDMetrics version: 0.14.1
* Python version: 3.12
* Operating System: Windows 11

### Error Description

Using the `Detection: Sequential` metric I get the following error: `ValueError: Found unknown categories ['2023-11-12 12:52:00', '2024-01-15 02:00:30' ...`
in lines 84 and 42 of file `...\sdmetrics\timeseries\detection.py` and line 213 of `...\sklearn\preprocessing\_encoders.py`

The metadata for this column is
`
        "date": {
            "sdtype": "datetime",
            "datetime_format": "%Y-%m-%d %H:%M:%S"
        },
`

### Steps to reproduce

As the original data is confidential I can't share it here. However, the following steps lead to the described error:. So maybe any dataset with a datetime column would be sufficient to reproduce the error.

```
synthesizer = PARSynthesizer( metadata, enforce_min_max_values=True, enforce_rounding=False, epochs=100, context_columns=['ContextColumn1'], verbose=True )

synthesizer.fit(real_data)

synthetic_data = synthesizer.sample( num_sequences=20, sequence_length=None )

LSTMDetection.compute(
    real_data=real_data,
    synthetic_data=synthetic_data,
    metadata=metadata,
    sequence_key='user_id'
)
```

### Temporary solution

The issue is due to the default behavior of the OneHotEncoder of the sklearn package, which throws an error in case of values in the synthetic data which were not present in the training data. Changing line 161 of file `\Lib\site-packages\sdmetrics\utils.py` from `enc = OneHotEncoder()` to `enc = OneHotEncoder(handle_unknown='ignore')` solves this issue.

So I would suggest:

1. give the user the option to define this parameter already in `LSTMDetection.compute` or
2. changing the default OneHotEncoder creation in utils.py, because this issue will probably occur in all datasets with a datetime.

**Comment by Ng-ms** [comment] 2024-06-04 16:45
hi @Scit3ch  thank you for providing the solution, however once I apply this solution I am getting this error 
`    sequences.append(torch.FloatTensor(sequence).T)
TypeError: only size-1 arrays can be converted to Python scalars`  do you have any idea how to fix this

**Comment by Ng-ms** [comment] 2024-06-04 17:45
hi @Scit3ch thank you for providing the solution, however once I apply this solution I am getting this error
`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
`do you have any idea how to fix this

**Comment by Scit3ch** [comment] 2024-06-05 06:22
@Ng-ms 
My guess would be that you have null/nan ('isnan') values somewhere in your data, but really hard to say without more information. As this has probably nothing to do with the bug I'm describing here maybe update your SDV, SDVMetrics and Python version first and if the error is still present open a new issue giving more information how and where this error occurs.

**Comment by srinify** [comment] 2024-06-07 16:55
Hi @Scit3ch thanks for filing this excellent bug report! I was able to reproduce the issue and I opened a new ticket here for the team to look at: https://github.com/sdv-dev/SDMetrics/issues/584

Can you try the following workaround to see if that resolves the issue? If it does, I can close this one out and we can focus the discussion on my bug report! Or there may be something else going on that we need to get to the bottom of!

### Suggested Workaround

For now, manually cast your datetime columns to the datetime dtype before using LSTMDetection. One quick way is using `pandas.to_datetime()`:

```
df['date_col_1'] = pd.to_datetime(df['date_col_1'])
```

**Comment by srinify** [comment] 2024-06-10 13:25
Duplicate of #584 1584

**Closed** 2024-06-10 13:26 UTC
Labels: bug, resolution:duplicate

**Comment by Scit3ch** [comment] 2024-06-10 13:39
Hi @srinify 
Thank you for the provided workaround which works.

One more thing: I've noticed that for the Metric 'StatisticSimilarity' one also needs to manually cast datetime columns when they were read via the 'load_csvs' function (maybe because this function reads datetime columns as object columns and only gets the required information via the metadata file). As this metric doesn't receive metadata information your ideal solution pictured in #584 wouldn't work here. A meaningful error message would be helpful here too.

**Comment by npatki** [comment] 2024-06-10 15:34
Hi @Scit3ch thanks for reporting. Most of the metrics in SDMetrics don't receive metadata information and don't do any conversions. They expect the inputted data to be in the correct format already (eg. datetimes converted from string to datetime). I agree a meaningful error message would be good there.

Could you file a separate issue for this so we can resolve it separately? 

For reference, [here are the docs](https://docs.sdv.dev/sdmetrics/metrics/metrics-glossary/statisticsimilarity) for statistic similarity. We will add clarifications there too.
